FORMAT: 1A

# Messages API

# Authentication [/access_tokens]
## Login user [POST]

+ Request
    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "email": "test@example.com",
              "password": "password"
            }

+ Response 201
    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "access_token": "access_token"
            }


# Message [/messages]

## Get all messages [GET]

+ Response 401

+ Request
    + Headers

            Content-Type: application/json; charset=utf-8
            Authorization: Bearer ABC123

+ Response 200
    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            [
              {
                "id": 1,
                "content": "Message 1"
              }
            ]

# Message [/messages/{id}]

## Show single message [GET]

+ Parameters
    + id: `1` (number, required) - Id of a message.

+ Response 401

+ Request
    + Headers

            Content-Type: application/json;charset=utf-8
            Authorization: Bearer ABC123

+ Response 200
    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "id": 1,
              "content": "Message 1"
            }
